// <auto-generated />
using System;
using LKN.Order.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace LKN.Order.Migrations
{
    [DbContext(typeof(OrderHttpApiHostMigrationsDbContext))]
    [Migration("20230919060910_orderserver")]
    partial class orderserver
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.MySql)
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LKN.Order.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime?>("Createtime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("longtext")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("OrderAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("OrderName")
                        .HasColumnType("longtext");

                    b.Property<string>("OrderRemark")
                        .HasColumnType("longtext");

                    b.Property<string>("OrderSn")
                        .HasColumnType("longtext");

                    b.Property<int?>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<string>("OrderTel")
                        .HasColumnType("longtext");

                    b.Property<string>("OrderTotalPrice")
                        .HasColumnType("longtext");

                    b.Property<string>("OrderType")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Paytime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Sendtime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Successtime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Updatetime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("LKN.Order.Orders.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("ItemCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("ItemPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ItemTotalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid?>("OrderId")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("OrderSn")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ProductName")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductUrl")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("LKN.Order.Orders.OrderItem", b =>
                {
                    b.HasOne("LKN.Order.Orders.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LKN.Order.Orders.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
